apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geth.secretname" . }}
stringData:
  {{- if .Values.authrpc.jwtSecret.file }}
  {{ .Values.authrpc.jwtSecret.filename }}: {{ .Values.authrpc.jwtSecret.file }}
  {{- end }}
  {{- if .Values.dataDirPassword.file }}
  {{ .Values.dataDirPassword.filename }}: {{ .Values.dataDirPassword.file }}
  {{- end }}
  {{- if .Values.blockSignerKey.file }}
  {{ .Values.blockSignerKey.filename }}: {{ .Values.blockSignerKey.file }}
  {{- end }}
