apiVersion: v1
kind: Secret
metadata:
  name: {{ include "op-node.secretname" . }}
stringData:
  {{- if .Values.l2.jwtSecret.file }}
  {{ .Values.l2.jwtSecret.filename }}: {{ .Values.l2.jwtSecret.file }}
  {{- end }}

  {{- if .Values.p2p.priv.file }}
  {{ .Values.p2p.priv.filename }}: {{ .Values.p2p.priv.file }}
  {{- end }}
