replicaCount: 1

image:
  repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

#######################################
# op-node settings for Goerli testnet.
#######################################
livenessProbe: true
readinessProbe: true

secretForVolumeMountDir: /secrets
configmapsForVolumeMountDir: /configmaps

l1:
  rpcAddr: https://ethereum-goerli-rpc.allthatnode.com
  rpcKind: "basic"

l2:
  rpcAddr:
  jwtSecret:
    file: # insert a file
    filename: jwt-secret.txt # file path to store jwtSecret

sequencer:
  enabled: true
  l1Confirmations: 3
  p2pKey:

verifier:
  l1Confirmations: 3

p2p:
  enabled: false
  priv:
    file:
    filename: p2ppriv.txt # file path to store p2p.priv
  listen:
    ip: 0.0.0.0
    tcp:
      name: p2p-tcp-port
      containerPort: 9003
      hostPort: 9003
    udp:
      name: p2p-udp-port
      containerPort: 9003
      hostPort: 9003

rollupConfig:
  filename: rollup.json

rpc:
  port:
    name: rpc-port
    containerPort: 8547
    hostPort: 8547
  addr: 0.0.0.0
  enableAdmin: true

metrics:
  enabled: true
  addr: 0.0.0.0
  port:
    name: metrics-port
    containerPort: 7300
    hostPort: 7300

pprof:
  enabled: true
  addr: 0.0.0.0
  port:
    name: pprof-port
    containerPort: 6060
    hostPort: 6060

# rest application arguments
args: []
