apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "op-batcher.fullname" . }}
  labels:
    {{- include "op-batcher.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "op-batcher.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "op-batcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "op-batcher.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.rpc.port.name }}
              containerPort: {{ .Values.rpc.port.containerPort }}
          command:
            - op-batcher
          args:
            - --l2-eth-rpc={{ required "L2 Execution Engine Address is required." .Values.l2.rpcAddr }}
            - --rollup-rpc={{ required "L2 Rollup Address is required." .Values.l2.rollupAddr }}
            - --poll-interval={{ .Values.l2.pollInterval }}
            - --sub-safety-margin={{ .Values.l2.subSafetyMargin }}
            - --num-confirmations={{ .Values.l2.numConfirmations }}
            - --safe-abort-nonce-too-low-count={{ .Values.l2.safeAbortNonceTooLowCount }}
            - --resubmission-timeout={{ .Values.l2.resubmissionTimeout }}
            - --rpc.addr={{ .Values.rpc.addr }}
            - --rpc.port={{ .Values.rpc.port.containerPort }}
            - --rpc.enable-admin={{ .Values.rpc.enableAdmin }}
            - --max-channel-duration={{ .Values.l2.maxChannelDuration }}
            - --l1-eth-rpc={{ .Values.l1.rpcAddr }}

            {{- with .Values.args }}
            # Rest Arguments
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: OP_BATCHER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "op-batcher.secretname" . }}
                  key: batcherKey
          {{- if .Values.livenessProbe }}
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 60
            tcpSocket:
              port: {{ .Values.rpc.port.name }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            # TODO: replace it to real http request.
            initialDelaySeconds: 15
            periodSeconds: 60
            tcpSocket:
              port: {{ .Values.rpc.port.name }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
